wordpress:
  image: wordpress:4.7
  links:
    - db:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=example
  ports:
    - "10084:80"

db:
  image: mariadb:10.1.13
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: wordpress
